import './globals.css'
import React from 'react'
import Provider from './Provider'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import { Navbar } from './components/Navbar'
import HeaderHome from './components/HeroHome'

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Shopping Cart',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='dark'>
      <body className={raleway.className}>
        <Provider>
          <header>
            <Navbar />
            <HeaderHome />
          </header>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  )
}
